# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-06 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='company_id',
            new_name='company',
        ),
    ]
